// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// level_infer_cpp
List level_infer_cpp(const NumericMatrix& w_mat, const IntegerMatrix& cfg, double alpha, double null_th, double ppa_min);
RcppExport SEXP _apch_level_infer_cpp(SEXP w_matSEXP, SEXP cfgSEXP, SEXP alphaSEXP, SEXP null_thSEXP, SEXP ppa_minSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type w_mat(w_matSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type cfg(cfgSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type null_th(null_thSEXP);
    Rcpp::traits::input_parameter< double >::type ppa_min(ppa_minSEXP);
    rcpp_result_gen = Rcpp::wrap(level_infer_cpp(w_mat, cfg, alpha, null_th, ppa_min));
    return rcpp_result_gen;
END_RCPP
}
// gaussian_posterior_cpp
Rcpp::List gaussian_posterior_cpp(const Rcpp::NumericMatrix& X, const Rcpp::NumericMatrix& S, const Rcpp::NumericMatrix& R_cor, const Rcpp::NumericMatrix& w_mat, const Rcpp::IntegerMatrix& cfg, const Rcpp::List& grid_list, const Rcpp::List& pi_list, bool return_cov_full, double w_thresh);
RcppExport SEXP _apch_gaussian_posterior_cpp(SEXP XSEXP, SEXP SSEXP, SEXP R_corSEXP, SEXP w_matSEXP, SEXP cfgSEXP, SEXP grid_listSEXP, SEXP pi_listSEXP, SEXP return_cov_fullSEXP, SEXP w_threshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type R_cor(R_corSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type w_mat(w_matSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type cfg(cfgSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type grid_list(grid_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pi_list(pi_listSEXP);
    Rcpp::traits::input_parameter< bool >::type return_cov_full(return_cov_fullSEXP);
    Rcpp::traits::input_parameter< double >::type w_thresh(w_threshSEXP);
    rcpp_result_gen = Rcpp::wrap(gaussian_posterior_cpp(X, S, R_cor, w_mat, cfg, grid_list, pi_list, return_cov_full, w_thresh));
    return rcpp_result_gen;
END_RCPP
}
// gaussian_posterior_xwas_cpp
Rcpp::List gaussian_posterior_xwas_cpp(const Rcpp::NumericMatrix& X, const Rcpp::NumericMatrix& S, const Rcpp::List& C_list, const Rcpp::NumericMatrix& w_mat, const Rcpp::IntegerMatrix& cfg, const Rcpp::List& grid_list, const Rcpp::List& pi_list, bool return_cov_full, double w_thresh);
RcppExport SEXP _apch_gaussian_posterior_xwas_cpp(SEXP XSEXP, SEXP SSEXP, SEXP C_listSEXP, SEXP w_matSEXP, SEXP cfgSEXP, SEXP grid_listSEXP, SEXP pi_listSEXP, SEXP return_cov_fullSEXP, SEXP w_threshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type C_list(C_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type w_mat(w_matSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type cfg(cfgSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type grid_list(grid_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pi_list(pi_listSEXP);
    Rcpp::traits::input_parameter< bool >::type return_cov_full(return_cov_fullSEXP);
    Rcpp::traits::input_parameter< double >::type w_thresh(w_threshSEXP);
    rcpp_result_gen = Rcpp::wrap(gaussian_posterior_xwas_cpp(X, S, C_list, w_mat, cfg, grid_list, pi_list, return_cov_full, w_thresh));
    return rcpp_result_gen;
END_RCPP
}
// block_stageA_cpp
List block_stageA_cpp(const NumericMatrix& X, const NumericMatrix& S, const NumericMatrix& Rcor, const List& sgL, const std::vector<std::vector<int>>& eta_list, const NumericVector& eta_init, std::string prior, std::string solver, double max_iter, double tol, bool progress, int progress_chunk, bool use_parallel, int n_threads, bool verbose);
RcppExport SEXP _apch_block_stageA_cpp(SEXP XSEXP, SEXP SSEXP, SEXP RcorSEXP, SEXP sgLSEXP, SEXP eta_listSEXP, SEXP eta_initSEXP, SEXP priorSEXP, SEXP solverSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP progressSEXP, SEXP progress_chunkSEXP, SEXP use_parallelSEXP, SEXP n_threadsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Rcor(RcorSEXP);
    Rcpp::traits::input_parameter< const List& >::type sgL(sgLSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<int>>& >::type eta_list(eta_listSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type eta_init(eta_initSEXP);
    Rcpp::traits::input_parameter< std::string >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< std::string >::type solver(solverSEXP);
    Rcpp::traits::input_parameter< double >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type progress(progressSEXP);
    Rcpp::traits::input_parameter< int >::type progress_chunk(progress_chunkSEXP);
    Rcpp::traits::input_parameter< bool >::type use_parallel(use_parallelSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(block_stageA_cpp(X, S, Rcor, sgL, eta_list, eta_init, prior, solver, max_iter, tol, progress, progress_chunk, use_parallel, n_threads, verbose));
    return rcpp_result_gen;
END_RCPP
}
// block_stageA_xwas_cpp
List block_stageA_xwas_cpp(const NumericMatrix& X, const NumericMatrix& S, const List& Rcor_list, const List& sgL, const std::vector<std::vector<int>>& eta_list, const NumericVector& eta_init, std::string prior, std::string solver, double max_iter, double tol, bool progress, int progress_chunk, bool use_parallel, int n_threads, bool verbose);
RcppExport SEXP _apch_block_stageA_xwas_cpp(SEXP XSEXP, SEXP SSEXP, SEXP Rcor_listSEXP, SEXP sgLSEXP, SEXP eta_listSEXP, SEXP eta_initSEXP, SEXP priorSEXP, SEXP solverSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP progressSEXP, SEXP progress_chunkSEXP, SEXP use_parallelSEXP, SEXP n_threadsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const List& >::type Rcor_list(Rcor_listSEXP);
    Rcpp::traits::input_parameter< const List& >::type sgL(sgLSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<int>>& >::type eta_list(eta_listSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type eta_init(eta_initSEXP);
    Rcpp::traits::input_parameter< std::string >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< std::string >::type solver(solverSEXP);
    Rcpp::traits::input_parameter< double >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type progress(progressSEXP);
    Rcpp::traits::input_parameter< int >::type progress_chunk(progress_chunkSEXP);
    Rcpp::traits::input_parameter< bool >::type use_parallel(use_parallelSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(block_stageA_xwas_cpp(X, S, Rcor_list, sgL, eta_list, eta_init, prior, solver, max_iter, tol, progress, progress_chunk, use_parallel, n_threads, verbose));
    return rcpp_result_gen;
END_RCPP
}
// block_stageA_predict_cpp
Rcpp::NumericMatrix block_stageA_predict_cpp(const NumericMatrix& X, const NumericMatrix& S, const NumericMatrix& Rcor, const List& sgL, const std::vector<std::vector<int>>& eta_list, const NumericVector& omega, std::string prior, bool progress, int progress_chunk, bool use_parallel, bool verbose);
RcppExport SEXP _apch_block_stageA_predict_cpp(SEXP XSEXP, SEXP SSEXP, SEXP RcorSEXP, SEXP sgLSEXP, SEXP eta_listSEXP, SEXP omegaSEXP, SEXP priorSEXP, SEXP progressSEXP, SEXP progress_chunkSEXP, SEXP use_parallelSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Rcor(RcorSEXP);
    Rcpp::traits::input_parameter< const List& >::type sgL(sgLSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<int>>& >::type eta_list(eta_listSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< std::string >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< bool >::type progress(progressSEXP);
    Rcpp::traits::input_parameter< int >::type progress_chunk(progress_chunkSEXP);
    Rcpp::traits::input_parameter< bool >::type use_parallel(use_parallelSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(block_stageA_predict_cpp(X, S, Rcor, sgL, eta_list, omega, prior, progress, progress_chunk, use_parallel, verbose));
    return rcpp_result_gen;
END_RCPP
}
// block_stageA_loglinear_cpp
Rcpp::List block_stageA_loglinear_cpp(const NumericMatrix& X, const NumericMatrix& S, const NumericMatrix& Rcor, const List& sgL, const std::vector<std::vector<int>>& eta_list, const NumericVector& eta_init, std::string prior, double lambda_A, int max_em, double tol, bool progress, int progress_chunk, bool use_parallel, int n_threads, bool verbose);
RcppExport SEXP _apch_block_stageA_loglinear_cpp(SEXP XSEXP, SEXP SSEXP, SEXP RcorSEXP, SEXP sgLSEXP, SEXP eta_listSEXP, SEXP eta_initSEXP, SEXP priorSEXP, SEXP lambda_ASEXP, SEXP max_emSEXP, SEXP tolSEXP, SEXP progressSEXP, SEXP progress_chunkSEXP, SEXP use_parallelSEXP, SEXP n_threadsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Rcor(RcorSEXP);
    Rcpp::traits::input_parameter< const List& >::type sgL(sgLSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<int>>& >::type eta_list(eta_listSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type eta_init(eta_initSEXP);
    Rcpp::traits::input_parameter< std::string >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_A(lambda_ASEXP);
    Rcpp::traits::input_parameter< int >::type max_em(max_emSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type progress(progressSEXP);
    Rcpp::traits::input_parameter< int >::type progress_chunk(progress_chunkSEXP);
    Rcpp::traits::input_parameter< bool >::type use_parallel(use_parallelSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(block_stageA_loglinear_cpp(X, S, Rcor, sgL, eta_list, eta_init, prior, lambda_A, max_em, tol, progress, progress_chunk, use_parallel, n_threads, verbose));
    return rcpp_result_gen;
END_RCPP
}
// block_stageA_xwas_loglinear_cpp
Rcpp::List block_stageA_xwas_loglinear_cpp(const NumericMatrix& X, const NumericMatrix& S, const List& Rcor_list, const List& sgL, const std::vector<std::vector<int>>& eta_list, const NumericVector& eta_init, std::string prior, double lambda_A, int max_em, double tol, bool progress, int progress_chunk, bool use_parallel, int n_threads, bool verbose);
RcppExport SEXP _apch_block_stageA_xwas_loglinear_cpp(SEXP XSEXP, SEXP SSEXP, SEXP Rcor_listSEXP, SEXP sgLSEXP, SEXP eta_listSEXP, SEXP eta_initSEXP, SEXP priorSEXP, SEXP lambda_ASEXP, SEXP max_emSEXP, SEXP tolSEXP, SEXP progressSEXP, SEXP progress_chunkSEXP, SEXP use_parallelSEXP, SEXP n_threadsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const List& >::type Rcor_list(Rcor_listSEXP);
    Rcpp::traits::input_parameter< const List& >::type sgL(sgLSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<int>>& >::type eta_list(eta_listSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type eta_init(eta_initSEXP);
    Rcpp::traits::input_parameter< std::string >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_A(lambda_ASEXP);
    Rcpp::traits::input_parameter< int >::type max_em(max_emSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type progress(progressSEXP);
    Rcpp::traits::input_parameter< int >::type progress_chunk(progress_chunkSEXP);
    Rcpp::traits::input_parameter< bool >::type use_parallel(use_parallelSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(block_stageA_xwas_loglinear_cpp(X, S, Rcor_list, sgL, eta_list, eta_init, prior, lambda_A, max_em, tol, progress, progress_chunk, use_parallel, n_threads, verbose));
    return rcpp_result_gen;
END_RCPP
}
// block_stageB_cpp
List block_stageB_cpp(const List& block_logf, const IntegerMatrix& cfg, const NumericVector& phi_init, int p, double max_iter, double tol, bool verbose, std::string solver);
RcppExport SEXP _apch_block_stageB_cpp(SEXP block_logfSEXP, SEXP cfgSEXP, SEXP phi_initSEXP, SEXP pSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP verboseSEXP, SEXP solverSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type block_logf(block_logfSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type cfg(cfgSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type phi_init(phi_initSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< std::string >::type solver(solverSEXP);
    rcpp_result_gen = Rcpp::wrap(block_stageB_cpp(block_logf, cfg, phi_init, p, max_iter, tol, verbose, solver));
    return rcpp_result_gen;
END_RCPP
}
// block_stageB_loglinear_cpp
Rcpp::List block_stageB_loglinear_cpp(const Rcpp::List& block_logf, const Rcpp::IntegerMatrix& cfg, double lambda, int max_em, double tol, bool verbose);
RcppExport SEXP _apch_block_stageB_loglinear_cpp(SEXP block_logfSEXP, SEXP cfgSEXP, SEXP lambdaSEXP, SEXP max_emSEXP, SEXP tolSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type block_logf(block_logfSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type cfg(cfgSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type max_em(max_emSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(block_stageB_loglinear_cpp(block_logf, cfg, lambda, max_em, tol, verbose));
    return rcpp_result_gen;
END_RCPP
}
// block_stageB_mcmc_cpp
List block_stageB_mcmc_cpp(const List& block_logf, const IntegerMatrix& cfg, int p, bool verbose);
RcppExport SEXP _apch_block_stageB_mcmc_cpp(SEXP block_logfSEXP, SEXP cfgSEXP, SEXP pSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type block_logf(block_logfSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type cfg(cfgSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(block_stageB_mcmc_cpp(block_logf, cfg, p, verbose));
    return rcpp_result_gen;
END_RCPP
}
// block_stageB_predict_cpp
Rcpp::NumericMatrix block_stageB_predict_cpp(const List& block_logf, const IntegerMatrix& cfg, const NumericVector& delta, int p, bool verbose);
RcppExport SEXP _apch_block_stageB_predict_cpp(SEXP block_logfSEXP, SEXP cfgSEXP, SEXP deltaSEXP, SEXP pSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type block_logf(block_logfSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type cfg(cfgSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(block_stageB_predict_cpp(block_logf, cfg, delta, p, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_apch_level_infer_cpp", (DL_FUNC) &_apch_level_infer_cpp, 5},
    {"_apch_gaussian_posterior_cpp", (DL_FUNC) &_apch_gaussian_posterior_cpp, 9},
    {"_apch_gaussian_posterior_xwas_cpp", (DL_FUNC) &_apch_gaussian_posterior_xwas_cpp, 9},
    {"_apch_block_stageA_cpp", (DL_FUNC) &_apch_block_stageA_cpp, 15},
    {"_apch_block_stageA_xwas_cpp", (DL_FUNC) &_apch_block_stageA_xwas_cpp, 15},
    {"_apch_block_stageA_predict_cpp", (DL_FUNC) &_apch_block_stageA_predict_cpp, 11},
    {"_apch_block_stageA_loglinear_cpp", (DL_FUNC) &_apch_block_stageA_loglinear_cpp, 15},
    {"_apch_block_stageA_xwas_loglinear_cpp", (DL_FUNC) &_apch_block_stageA_xwas_loglinear_cpp, 15},
    {"_apch_block_stageB_cpp", (DL_FUNC) &_apch_block_stageB_cpp, 8},
    {"_apch_block_stageB_loglinear_cpp", (DL_FUNC) &_apch_block_stageB_loglinear_cpp, 6},
    {"_apch_block_stageB_mcmc_cpp", (DL_FUNC) &_apch_block_stageB_mcmc_cpp, 4},
    {"_apch_block_stageB_predict_cpp", (DL_FUNC) &_apch_block_stageB_predict_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_apch(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
