# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

level_infer_cpp <- function(w_mat, cfg, alpha = 0.05, null_th = 0.9, ppa_min = 0.2) {
    .Call(`_apch_level_infer_cpp`, w_mat, cfg, alpha, null_th, ppa_min)
}

gaussian_posterior_cpp <- function(X, S, R_cor, w_mat, cfg, grid_list, pi_list, return_cov_full = TRUE, w_thresh = 1e-12) {
    .Call(`_apch_gaussian_posterior_cpp`, X, S, R_cor, w_mat, cfg, grid_list, pi_list, return_cov_full, w_thresh)
}

gaussian_posterior_xwas_cpp <- function(X, S, C_list, w_mat, cfg, grid_list, pi_list, return_cov_full = TRUE, w_thresh = 1e-12) {
    .Call(`_apch_gaussian_posterior_xwas_cpp`, X, S, C_list, w_mat, cfg, grid_list, pi_list, return_cov_full, w_thresh)
}

block_stageA_cpp <- function(X, S, Rcor, sgL, eta_list, eta_init, prior = "normal", solver = "mixsqp", max_iter = 1e6, tol = 1e-6, progress = TRUE, progress_chunk = 64L, use_parallel = TRUE, n_threads = 8L, verbose = TRUE) {
    .Call(`_apch_block_stageA_cpp`, X, S, Rcor, sgL, eta_list, eta_init, prior, solver, max_iter, tol, progress, progress_chunk, use_parallel, n_threads, verbose)
}

block_stageA_xwas_cpp <- function(X, S, Rcor_list, sgL, eta_list, eta_init, prior = "normal", solver = "mixsqp", max_iter = 1e6, tol = 1e-6, progress = TRUE, progress_chunk = 64L, use_parallel = TRUE, n_threads = 8L, verbose = TRUE) {
    .Call(`_apch_block_stageA_xwas_cpp`, X, S, Rcor_list, sgL, eta_list, eta_init, prior, solver, max_iter, tol, progress, progress_chunk, use_parallel, n_threads, verbose)
}

block_stageA_predict_cpp <- function(X, S, Rcor, sgL, eta_list, omega, prior = "normal", progress = TRUE, progress_chunk = 64L, use_parallel = TRUE, verbose = TRUE) {
    .Call(`_apch_block_stageA_predict_cpp`, X, S, Rcor, sgL, eta_list, omega, prior, progress, progress_chunk, use_parallel, verbose)
}

block_stageA_loglinear_cpp <- function(X, S, Rcor, sgL, eta_list, eta_init, prior = "normal", lambda_A = 0.05, max_em = 500L, tol = 1e-2, progress = TRUE, progress_chunk = 64L, use_parallel = TRUE, n_threads = 8L, verbose = TRUE) {
    .Call(`_apch_block_stageA_loglinear_cpp`, X, S, Rcor, sgL, eta_list, eta_init, prior, lambda_A, max_em, tol, progress, progress_chunk, use_parallel, n_threads, verbose)
}

block_stageA_xwas_loglinear_cpp <- function(X, S, Rcor_list, sgL, eta_list, eta_init, prior = "normal", lambda_A = 0.05, max_em = 500L, tol = 1e-2, progress = TRUE, progress_chunk = 64L, use_parallel = TRUE, n_threads = 8L, verbose = TRUE) {
    .Call(`_apch_block_stageA_xwas_loglinear_cpp`, X, S, Rcor_list, sgL, eta_list, eta_init, prior, lambda_A, max_em, tol, progress, progress_chunk, use_parallel, n_threads, verbose)
}

block_stageB_cpp <- function(block_logf, cfg, phi_init, p, max_iter = 1e6, tol = 1e-6, verbose = TRUE, solver = "mixsqp") {
    .Call(`_apch_block_stageB_cpp`, block_logf, cfg, phi_init, p, max_iter, tol, verbose, solver)
}

block_stageB_loglinear_cpp <- function(block_logf, cfg, lambda = NA_real_, max_em = 500L, tol = 1e-2, verbose = TRUE) {
    .Call(`_apch_block_stageB_loglinear_cpp`, block_logf, cfg, lambda, max_em, tol, verbose)
}

block_stageB_mcmc_cpp <- function(block_logf, cfg, p, verbose = TRUE) {
    .Call(`_apch_block_stageB_mcmc_cpp`, block_logf, cfg, p, verbose)
}

block_stageB_predict_cpp <- function(block_logf, cfg, delta, p, verbose = TRUE) {
    .Call(`_apch_block_stageB_predict_cpp`, block_logf, cfg, delta, p, verbose)
}

